### ISSUE TITLE
Support Windows PDBs

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#153]
This is necessary for C++ packages. See: https://twitter.com/dotMorten/status/1070402827112013824

Follow up to: https://github.com/loic-sharma/BaGet/issues/130

**Comment by Kilowhisky** [comment]
Just throwing my 2 cents into this for google search indexing purposes because it took for ever to figure out that the app only supports PortablePDB format.

When you try and submit a  .nupkg / .snupkg that was built with any options other than `portable`.

![image](https://user-images.githubusercontent.com/7075666/50301142-5bb9de00-043b-11e9-8611-e24426d86389.png)

 The server will throw a  400 (bad request) and the sdtout log will have the following:

````
fail: BaGet.Core.Services.SymbolIndexingService[0]
      Unable to index symbol package due to exception
System.BadImageFormatException: Invalid COR20 header signature.
   at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader, String& versionString)
   at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder, Object memoryOwner)
   at System.Reflection.Metadata.MetadataReaderProvider.GetMetadataReader(MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
   at BaGet.Core.Services.SymbolIndexingService.ExtractPortablePdbAsync(PackageArchiveReader symbolPackage, String pdbPath, CancellationToken cancellationToken) in D:\a\1\s\src\BaGet.Core\Services\SymbolIndexingService.cs:line 158
   at BaGet.Core.Services.SymbolIndexingService.IndexAsync(Stream stream, CancellationToken cancellationToken) in D:\a\1\s\src\BaGet.Core\Services\SymbolIndexingService.cs:line 72
````

The solution for regular old .NET Framework packages is to change the debugging information to the 'portable' type. This will then properly upload the packages.

**Comment by loic-sharma** [comment]
Sorry about that! BaGet should return a better error message if the PDB isn’t portable. Ideally, this error message should be reported back to the NuGet client that tried the push operation.

**Comment by adeweever** [comment]
@loic-sharma We just started using Baget and so far so good, but we would love to see this issue resolved to aid our devs in debugging. Is there any updates on this?

**Comment by jacksga** [comment]
Same here, I recently found out about Baget and would love to use it instead of the oldish Nuget.Server but we'd love to use the symbol server feature with Windows PDBs. Any chance to get support for those any time soon @loic-sharma? 😅

**Comment by Duracell1989** [comment]
> 
> 
> Just throwing my 2 cents into this for google search indexing purposes because it took for ever to figure out that the app only supports PortablePDB format.
> 
> When you try and submit a .nupkg / .snupkg that was built with any options other than `portable`.
> 
> ![image](https://user-images.githubusercontent.com/7075666/50301142-5bb9de00-043b-11e9-8611-e24426d86389.png)
> 
> The server will throw a 400 (bad request) and the sdtout log will have the following:
> 
> ```
> fail: BaGet.Core.Services.SymbolIndexingService[0]
>       Unable to index symbol package due to exception
> System.BadImageFormatException: Invalid COR20 header signature.
>    at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader, String& versionString)
>    at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder, Object memoryOwner)
>    at System.Reflection.Metadata.MetadataReaderProvider.GetMetadataReader(MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
>    at BaGet.Core.Services.SymbolIndexingService.ExtractPortablePdbAsync(PackageArchiveReader symbolPackage, String pdbPath, CancellationToken cancellationToken) in D:\a\1\s\src\BaGet.Core\Services\SymbolIndexingService.cs:line 158
>    at BaGet.Core.Services.SymbolIndexingService.IndexAsync(Stream stream, CancellationToken cancellationToken) in D:\a\1\s\src\BaGet.Core\Services\SymbolIndexingService.cs:line 72
> ```
> 
> The solution for regular old .NET Framework packages is to change the debugging information to the 'portable' type.
> 
> I still think the regular old Windows PDB format should be supported. Nuget / Microsoft have this nasty habit of changing things every couple years and leaving people to pick up the pieces and build in backwards compatibility.

I also ran into this problem. Thanks @Kilowhisky for specifying this.
In the mean time, maybe this can be documented in the readme that (currently) only portablePDB's are supported?

**Comment by MaxDobbelstein** [comment]
I am facing the same problem with .net 4.7.2 Symbol Package. Changing to portable PDBs did not work for me. am I missing something?

**Comment by JarrodJ83** [comment]
This is an issue for us as well. We use GitLab with two-factory authentication which means we cannot use Source Link. Next best thing would be to use BaGet as a symbol server but for Visual Studio to use a symbol server it must support Windows PDBs. Now we are stuck either switching our git provider or switching our package server until we are able to successfully debug our internal nuget packages :(
