### ISSUE TITLE
how to update port using dotnet BaGet.dll command

### ISSUE THREAD

**Issue by noahjzc** [loic-sharma/BaGet#173]
### how to update port using dotnet BaGet.dll command

using command to configure port like dotnet BaGet.dll --urls http://*:10000

**Comment by loic-sharma** [comment]
You can:

1. Pass the URL as a CLI option: `dotnet BaGet.dll --server.urls "http://*:10000"
2. Set the `ASPNETCORE_URLS` environment variable to `http://*:10000`

This blog lists lots of other options too: https://andrewlock.net/configuring-urls-with-kestrel-iis-and-iis-express-with-asp-net-core/

Let me know if you have any additional questions!

**Comment by noahjzc** [comment]
Thank you for reply. And I try to use `dotnet BaGet.dll --server.urls "http://*:10000"`, but it's an exception like this.
```
[root@dev baget]# dotnet BaGet.dll --server.urls "http://*:8100"
Specify --help for a list of available options and commands.

Unhandled Exception: McMaster.Extensions.CommandLineUtils.CommandParsingException: Unrecognized option '--server.urls'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.HandleUnexpectedArg(String argTypeName) in C:\projects\commandlineutils\src\CommandLineUtils\Internal\CommandLineProcessor.cs:line 246
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption() in C:\projects\commandlineutils\src\CommandLineUtils\Internal\CommandLineProcessor.cs:line 161
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext() in C:\projects\commandlineutils\src\CommandLineUtils\Internal\CommandLineProcessor.cs:line 62
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process() in C:\projects\commandlineutils\src\CommandLineUtils\Internal\CommandLineProcessor.cs:line 35
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 532
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 597
   at BaGet.Program.Main(String[] args) in D:\a\1\s\src\BaGet\Program.cs:line 44
Aborted
```

**Comment by loic-sharma** [comment]
Good catch, that's a bug. For now, I'd use the `ASPNETCORE_URLS` environment variable.

**Comment by noahjzc** [comment]
where can i configure the `ASPNETCORE_URLS` environment variable.
in `appsettings.json` like this?
```
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  },
  "ASPNETCORE_URLS": "http://*:8100"
}
```

**Comment by chenzuo** [comment]
"https://package.jiehai-tech.com/" 
This address is for everyone to use for testing. Everyone is welcome to use this address test. I will stare at the author's release every minute. As long as he updates, I will provide the latest test address.

**Comment by loic-sharma** [comment]
@noahjzc what operating system are you on? Setting a normal operating system environment variable should do the trick.

**Comment by loic-sharma** [comment]
The environment variable should do the trick. I'll close this off for now, but please let me know if you have any additional questions

**Comment by chenzuo** [comment]
OK！

**Comment by chenzuo** [comment]
ths！
