### ISSUE TITLE
exception when a package file is not found

### ISSUE THREAD

**Issue by gekkedev** [loic-sharma/BaGet#298]
### Describe the bug
Unhandled exception occurs when a package file was not found. Apparently updating _BaGet_ has messed up my package directory structure. I don't care that much about it. The following error could happen to anyone who plays around with file paths.

### To Reproduce
1. Using this version of BaGet 'master@4d627fa'
2. Play around with the file paths or the database (e.g. rename the package folder by accident)
3. Request the package
4. See log

### Work-around
Lowercase the `Packages` folder to `packages`.

### Expected behavior
A clear sentence about the nupkg file not being found; eventually stating that there is a discrepancy betweend database and filesystem. Anything than a bombardement of the log seems aight.

### Screenshots -> Logfile instead
```
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/nuget/new/src/BaGet/packages/packagename/1.10.7/packagename.1.10.7.nupkg'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at BaGet.Core.Storage.FileStorageService.GetAsync(String path, CancellationToken cancellationToken) in /home/nuget/new/src/BaGet.Core/Storage/FileStorageService.cs:line 36
   at BaGet.Core.Storage.PackageStorageService.GetStreamAsync(String id, NuGetVersion version, Func`3 pathFunc, CancellationToken cancellationToken) in /home/nuget/new/src/BaGet.Core/Storage/PackageStorageService.cs:line 157
   at BaGet.Core.Storage.PackageStorageService.GetPackageStreamAsync(String id, NuGetVersion version, CancellationToken cancellationToken) in /home/nuget/new/src/BaGet.Core/Storage/PackageStorageService.cs:line 120
   at BaGet.Controllers.PackageController.DownloadPackage(String id, String version, CancellationToken cancellationToken) in /home/nuget/new/src/BaGet.Core.Server/Controllers/PackageController.cs:line 64
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
```

**Comment by gekkedev** [comment]
Update:
I've found what caused the packages to not be found. Apparently the folder `Packages` was renamed  in da121ba327bf3358330f59898c5d0e201a9ac1ee by @loic-sharma to `packages` without keeping in mind that Linux paths are case sensitive. When using sofware based on .NET Core, I assumed that the application is designed to run on Linux as well. Renaming the folder in the code caused my BaGet installation to create a completely new package folder whilst letting the previous folder coexist without ever reading from or writing to it.

Dropping support for old versions is somewhat acceptable, but not being able to download **all** versions from one day to another is a breaking change. I strongly suggest fixing this, but not by renaming it back. Many users might have experienced the same issue, but you could provide a migration routine renaming the uppercase folder to lowercase **or** simply catching the exception: If the requested package (which is indexed in the database) was not found on the file system, it is the next logical thing to assume that this happened due to renaming the folder. Then all BaGet has to do is to repeat reading the file using the legacy folder name (unless there is a different reason, which will still trigger an exception).

**Comment by loic-sharma** [comment]
Thank you for reporting this!

> A clear sentence about the nupkg file not being found; eventually stating that there is a discrepancy betweend database and filesystem. Anything than a bombardement of the log seems aight.

I like this idea, I'll add that in!

> I've found what caused the packages to not be found. Apparently the folder Packages was renamed in da121ba by @loic-sharma to packages without keeping in mind that Linux paths are case sensitive. When using sofware based on .NET Core, I assumed that the application is designed to run on Linux as well. Renaming the folder in the code caused my BaGet installation to create a completely new package folder whilst letting the previous folder coexist without ever reading from or writing to it.

I develop mainly on Windows and did not test the upgrade scenario properly on all platforms. I will keep this in mind going forward. I apologize for the inconvenience 😅 

> you could provide a migration routine renaming the uppercase folder to lowercase or simply catching the exception: If the requested package (which is indexed in the database) was not found on the file system, it is the next logical thing to assume that this happened due to renaming the folder.

I'm a little torn about this. This suggestion would certainly ease the transition for customers, but this would be "dead" code for most users going forward. The customer could rename the folder to fix the issue if the error message is sufficiently clear. Do you think that'd be enough?

**Comment by loic-sharma** [comment]
It looks like this issue is related too: https://github.com/loic-sharma/BaGet/issues/302

**Comment by gekkedev** [comment]
> I'm a little torn about this. This suggestion would certainly ease the transition for customers, but this would be "dead" code for most users going forward. The customer could rename the folder to fix the issue if the error message is sufficiently clear. Do you think that'd be enough?

Well, renaming the folder from `packages` to `Packages` to fix the issue will not be possible if there have been any package updates after updating BaGet. In that scenario, two `packages`/`Packages` folders will exist with one subdirectory per package, each carrying subfolders named like the package versions. Merging them had (and has, for other users) to be done on a per-package basis. For my corporate use-case, it took me about three minutes for 10 packages using the shell **after** doing my research and going through the logs (screen is only useful if you don't need much logging 😉).
Regarding the exception: Although I think the ambivalent path should be handled by *BaGet*; I'll submit you a quick PR to point users into the right direction.

**Comment by loic-sharma** [comment]
An error message was added by @gekkedev in https://github.com/loic-sharma/BaGet/pull/346. If you have any additional issues, please let me know!
