### ISSUE TITLE
using BaGet offline with read-through caching fails instead of simply providing the cached version

### ISSUE THREAD

**Issue by stefanloerwald** [loic-sharma/BaGet#432]
### Describe the bug
When the internet connection is lost (yeah, I have that occasionally, as you can see from my other opened issue about offline usage. I develop while taking a train, from time to time), BaGet with read-through caching enabled seems to still try and fetch the most recent information about packages from the external source (e.g. nuget.org). Ideally, it should just hit the local cache, and retry to update external package information later (with exponential backoff).

### To Reproduce
1. Set up BaGet with read-through cache of nuget.org
2. Make sure at least one package is cached
3. Go offline
4. Try and restore a project using said package
5. Observe error 500 returned from BaGet

### Expected behavior
Hit cache even when offline, optionally retrying to fetch most recent info later when connectivity is restored.

**Comment by stefanloerwald** [comment]
Stacktrace from the BaGet log when the external source is not reached:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLRUB4KE281S", Request id "0HLRUB4KE281S:00000004": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at BaGet.Protocol.HttpClientExtensions.DeserializeUrlAsync[T](HttpClient httpClient, String documentUrl, CancellationToken cancellationToken) in /src/BaGet.Protocol/Extensions/HttpClientExtensions.cs:line 26
   at BaGet.Protocol.Internal.RawPackageContentClient.GetPackageVersionsOrNullAsync(String packageId, CancellationToken cancellationToken) in /src/BaGet.Protocol/PackageContent/RawPackageContentClient.cs:line 40
   at BaGet.Protocol.NuGetClientFactory.PackageContentClient.GetPackageVersionsOrNullAsync(String packageId, CancellationToken cancellationToken) in /src/BaGet.Protocol/PackageContent/PackageContentClient.cs:line 47
   at BaGet.Protocol.NuGetClient.ListPackageVersionsAsync(String packageId, Boolean includeUnlisted, CancellationToken cancellationToken) in /src/BaGet.Protocol/NuGetClient.cs:line 180
   at BaGet.Core.MirrorService.FindPackageVersionsOrNullAsync(String id, CancellationToken cancellationToken) in /src/BaGet.Core/Mirror/MirrorService.cs:line 39
   at BaGet.Core.Content.DefaultPackageContentService.GetPackageVersionsOrNullAsync(String id, CancellationToken cancellationToken) in /src/BaGet.Core/Content/DefaultPackageContentService.cs:line 37
   at BaGet.Controllers.PackageContentController.GetPackageVersionsAsync(String id, CancellationToken cancellationToken) in /src/BaGet.Core.Server/Controllers/PackageContentController.cs:line 26
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at BaGet.OperationCancelledMiddleware.Invoke(HttpContext context) in /src/BaGet.Core.Server/OperationCancelledMiddleware.cs:line 28
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by loic-sharma** [comment]
This has been fixed by the latest release. Please let me know if you have any additional issues or feedback!

**Comment by stefanloerwald** [comment]
Confirmed to be fixed. Great work, Thanks!
