### ISSUE TITLE
ArgumentNullException for autocompleteUrl using Azure Artifacts feed

### ISSUE THREAD

**Issue by bgrainger** [loic-sharma/BaGet#477]
When using `NuGetClient` with an Azure Artifacts feed, calling `GetPackageMetadataAsync` throws an `ArgumentNullException` for `autocompleteUrl`.

### To Reproduce

1. Create a public Azure Artifacts NuGet feed. I have an empty one at https://pkgs.dev.azure.com/mysqlnet/MySqlConnector/_packaging/test/nuget/v3/index.json
2. Install BaGet.Protocol 0.3.0-preview2
3. Run this code:

```csharp
var client = new NuGetClient("https://pkgs.dev.azure.com/mysqlnet/MySqlConnector/_packaging/test/nuget/v3/index.json");
await client.GetPackageMetadataAsync("Test");
```

4. There's an unhandled exception:

```
ArgumentNullException: Value cannot be null. (Parameter 'autocompleteUrl')
   at BaGet.Protocol.Internal.RawSearchClient..ctor(HttpClient httpClient, String searchUrl, String autocompleteUrl) in D:\a\1\s\src\BaGet.Protocol\Search\RawSearchClient.cs:line 33
   at BaGet.Protocol.NuGetClientFactory.GetAsync[T](Func`2 clientFactory, CancellationToken cancellationToken) in D:\a\1\s\src\BaGet.Protocol\NuGetClientFactory.cs:line 151
   at BaGet.Protocol.NuGetClientFactory.PackageMetadataClient.GetRegistrationIndexOrNullAsync(String packageId, CancellationToken cancellationToken) in D:\a\1\s\src\BaGet.Protocol\PackageMetadata\PackageMetadataClient.cs:line 24
   at BaGet.Protocol.NuGetClient.GetPackageMetadataAsync(String packageId, CancellationToken cancellationToken) in D:\a\1\s\src\BaGet.Protocol\NuGetClient.cs:line 200
```

### Expected behavior

That BaGet.Protocol should be able to retrieve package metadata from Azure Artifacts, even if all NuGet API v3 services aren't exposed.

**Comment by loic-sharma** [comment]
Thanks for reporting! Two fixes:

1. The autocomplete resource isn't required (see [this](https://docs.microsoft.com/en-us/nuget/api/overview#resources-and-schema)), BaGet.Protocol shouldn't assume it exists
1. BaGet.Protocol should throw a better exception if a resource it cannot find an expected resource

I'll fix this ASAP

**Comment by loic-sharma** [comment]
Okay this should be fixed! Let me know if you run into any additional issues

**Comment by loic-sharma** [comment]
I realize I forgot to publish updated packages. I've released v0.3.0-preview3 with the fixes, it should be available shortly: https://www.nuget.org/packages/BaGet.Protocol/0.3.0-preview3

**Comment by bgrainger** [comment]
Confirmed that preview3 works great; thanks!

**Comment by loic-sharma** [comment]
Awesome! Please let me know if you run into any additional issues or have any feedback
