### ISSUE TITLE
Unable to mirror package upstream versions

### ISSUE THREAD

**Issue by queil** [loic-sharma/BaGet#484]
### Describe the bug
Mirrored packages timeout on getting `https://{my-baget-instance}/v3/registration/{package-name}/index.json`.

In the UI getting this:
`(Could not find package 'iesi.collections')`

### To Reproduce
Either `dotnet restore` or on loading the package in the UI.

### Expected behavior
It doesn't timeout and I can successfully restore or view the package in the UI.

### Additional context
BaGet image: `loicsharma/baget:9c5a9f38896a5b70f6bc66b17c1c94543af39c2a`

Stack trace from the container:
```
fail: BaGet.Core.MirrorService[0]
      Unable to mirror package iesi.collections's upstream versions
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at BaGet.Protocol.HttpClientExtensions.DeserializeUrlAsync[T](HttpClient httpClient, String documentUrl, CancellationToken cancellationToken) in /src/BaGet.Protocol/Extensions/HttpClientExtensions.cs:line 55
   at BaGet.Protocol.Internal.RawServiceIndexClient.GetAsync(CancellationToken cancellationToken) in /src/BaGet.Protocol/ServiceIndex/RawServiceIndexClient.cs:line 38
   at BaGet.Protocol.NuGetClientFactory.GetAsync[T](Func`2 clientFactory, CancellationToken cancellationToken) in /src/BaGet.Protocol/NuGetClientFactory.cs:line 198
   at BaGet.Protocol.NuGetClientFactory.PackageContentClient.GetPackageVersionsOrNullAsync(String packageId, CancellationToken cancellationToken) in /src/BaGet.Protocol/PackageContent/PackageContentClient.cs:line 45
   at BaGet.Protocol.NuGetClient.ListPackageVersionsAsync(String packageId, Boolean includeUnlisted, CancellationToken cancellationToken) in /src/BaGet.Protocol/NuGetClient.cs:line 182
   at BaGet.Core.MirrorService.RunOrNull[T](String id, String data, Func`1 x) in /src/BaGet.Core/Mirror/MirrorService.cs:line 191
fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
      An error occurred using the connection to database 'main' on server '/var/baget/baget.db'.
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'BaGet.Database.Sqlite.SqliteContext'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
warn: BaGet.OperationCancelledMiddleware[0]
      Request cancelled
```

**Comment by queil** [comment]
I think it was related to some network issues because started working as expected shortly after I raised it.
