### ISSUE TITLE
Multiple mirrors

### ISSUE THREAD

**Issue by beachwalker** [loic-sharma/BaGet#497]
### Is your feature request related to a problem? Please describe.
When I want to mirror two or more nuget servers, I can't configure this. Otherwise I get:

```
Unhandled exception. System.FormatException: A duplicate key 'Mirror:Enabled' was found.
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.VisitValue(JsonElement value)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.VisitElement(JsonElement element)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.VisitValue(JsonElement value)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.VisitElement(JsonElement element)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at BaGet.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext() in D:\a\1\s\src\BaGet\Program.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<<OnExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at BaGet.Program.Main(String[] args) in D:\a\1\s\src\BaGet\Program.cs:line 51
   at BaGet.Program.<Main>(String[] args)
```

When I try it with a configuration like this:

```
  "Mirror": {
    "Enabled": true,
    "PackageSource": "https://api.nuget.org/v3/index.json"
  },

  "Mirror": {
    "Enabled": true,
    "PackageSource": "https://www.myget.org/F/caliburn-micro-builds/api/v3/index.json"
  },  
```

### Describe the solution you'd like
It would be nice if we could have more than one mirror. The mirroring should be like this. If you don't find it on the first mirror try the next one (like a chain).
This allows to add specific alternatives that may have already newer packages (e.g. like myget in this case).

### Describe alternatives you've considered
I could add multiple URLs to the project itself (nuget.config) but it would be nice if we could serve this by a single BaGet.

**Comment by beachwalker** [comment]
Did I understood correctly that a configured mirror makes BaGet act as proxy? Or is the mirror the "backup" for uploading from BaGet?

**Comment by beachwalker** [comment]
If it is the case that BaGet copies the remote package into its own local storage if a package is requested that is not found… then there might be a bug. When I point my project to BaGet (with mirroring nuget) the following message occurs (Debug level):

...
Connection id "0HLUHRQFENR66" sending FIN because: "The client closed the connection."
...
Connection id "0HLUHRQFENR65" sending FIN because: "The Socket transport's send loop completed gracefully."
...

Also only some packages are stored locally. The build/publish process stops with errors (not all packages are resolved). On the other hand if I use nuget directly everything works as expected. What makes me think that I am not totally wrong is that "some" packages are downloaded.

**Comment by WernerMairl** [comment]
Current BaGet implementation allows only ONE source for mirror.
The exception is caused by the config-subsystem because the "Mirror" item must be UNIQUE inside the appsettings.json.

So basically this is a feature request, that may need more spec specially about behavior:

- mirror 
- proxy 
- proxy with cache

regards
Werner

**Comment by Suriman** [comment]
Yes, please!

**Comment by juanperezADD** [comment]
Same problem. We have multiple packages sources that we would like to mirror.

**Comment by NecatiMeral** [comment]
I have a use-case too where I need two mirrors to apply read-through caching for.

1. nuget.org
2. another feed which is protected by a api key

**Comment by mattleibow** [comment]
I suppose it is possible to set up multiple mirrors by using multiple servers :)

**Comment by loic-sharma** [comment]
Yup you can always use multiple BaGet instances to support multiple mirrors (though that's a bit of a hassle).

A problem with this feature is that it makes BaGet users vulnerable to [package dependency confusion attacks](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610). We would likely want to take inspiration from NuGet's upcoming [package namespaces feature](https://github.com/NuGet/Home/blob/dev/proposed/2021/PackageNamespaces.md).

**Comment by jorgensigvardsson** [comment]
Would a PR for multiple mirrors be of interest? Ping @loic-sharma
