### ISSUE TITLE
Change ReleaseNotes to nvarchar(max) in DB schema for SqlServer

### ISSUE THREAD

**Issue by gimlichael** [loic-sharma/BaGet#590]
### Describe the bug
When uploading a NuGet package with a thorough release notes, an SqLException is thrown.
According to the specs of NuGet, 35.000 characters is allowed.
I recommend nvarchar(max) given the current design of your schema.

### To Reproduce
1. Docker image: loicsharma/baget:19dc5c514fcbfdeda0c06d67b526744733d827bb
2. Upload a NuGet package with long release notes

### Expected behavior
I would expect BaGet to conform with NuGet specifications: https://docs.microsoft.com/en-us/nuget/reference/nuspec

### Exception
```
2020-09-08T19:40:54.383725267Z fail: Microsoft.EntityFrameworkCore.Update[10000]
2020-09-08T19:40:54.383785367Z       An exception occurred in the database while saving changes for context type 'BaGet.Database.SqlServer.SqlServerContext'.
2020-09-08T19:40:54.383801268Z       Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
2020-09-08T19:40:54.383805368Z        ---> Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated in table 'devnuget.dbo.Packages', column 'ReleaseNotes'. Truncated value: 'Version: 6.0.0
2020-09-08T19:40:54.383808868Z       Availability: NET Standard 2.0
2020-09-08T19:40:54.383811768Z        
2020-09-08T19:40:54.383814968Z       # Upgrade Steps
2020-09-08T19:40:54.383817868Z       - The Cuemon.Serialization.Xml names'.
2020-09-08T19:40:54.383820768Z       The statement has been terminated.
2020-09-08T19:40:54.383823668Z          at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
2020-09-08T19:40:54.383827268Z          at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
2020-09-08T19:40:54.383829968Z          at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2020-09-08T19:40:54.383832868Z       --- End of stack trace from previous location where exception was thrown ---
2020-09-08T19:40:54.383835068Z          at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2020-09-08T19:40:54.383837368Z       --- End of stack trace from previous location where exception was thrown ---
2020-09-08T19:40:54.383839468Z          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
2020-09-08T19:40:54.383841768Z          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
2020-09-08T19:40:54.383844068Z          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
2020-09-08T19:40:54.383846368Z          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.383848568Z       ClientConnectionId:4354eea0-8955-4584-a17a-f3d5a1b11300
2020-09-08T19:40:54.383851768Z       Error Number:2628,State:1,Class:16
2020-09-08T19:40:54.383853868Z          --- End of inner exception stack trace ---
2020-09-08T19:40:54.383864869Z          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.383867369Z          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.383869669Z          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.383871869Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
2020-09-08T19:40:54.383874169Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2020-09-08T19:40:54.383876469Z          at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
2020-09-08T19:40:54.383879069Z          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2020-09-08T19:40:54.383881269Z Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
2020-09-08T19:40:54.383883569Z  ---> Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated in table 'devnuget.dbo.Packages', column 'ReleaseNotes'. Truncated value: 'Version: 6.0.0
2020-09-08T19:40:54.383885969Z Availability: NET Standard 2.0
2020-09-08T19:40:54.383887869Z  
2020-09-08T19:40:54.383889969Z # Upgrade Steps
2020-09-08T19:40:54.383891869Z - The Cuemon.Serialization.Xml names'.
2020-09-08T19:40:54.383893769Z The statement has been terminated.
2020-09-08T19:40:54.383895969Z    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
2020-09-08T19:40:54.383898369Z    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
2020-09-08T19:40:54.383900769Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2020-09-08T19:40:54.383903069Z --- End of stack trace from previous location where exception was thrown ---
2020-09-08T19:40:54.383905069Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2020-09-08T19:40:54.383907269Z --- End of stack trace from previous location where exception was thrown ---
2020-09-08T19:40:54.383909369Z    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
2020-09-08T19:40:54.383911569Z    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
2020-09-08T19:40:54.383916469Z    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
2020-09-08T19:40:54.383918969Z    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.383921269Z ClientConnectionId:4354eea0-8955-4584-a17a-f3d5a1b11300
2020-09-08T19:40:54.383923269Z Error Number:2628,State:1,Class:16
2020-09-08T19:40:54.383925169Z    --- End of inner exception stack trace ---
2020-09-08T19:40:54.383927169Z    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.383929369Z    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.383931569Z    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.38393397Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
2020-09-08T19:40:54.38393637Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2020-09-08T19:40:54.38394047Z    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
2020-09-08T19:40:54.38394297Z    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2020-09-08T19:40:54.387067612Z fail: BaGet.Hosting.PackagePublishController[0]
2020-09-08T19:40:54.387078513Z       Exception thrown during package upload
2020-09-08T19:40:54.387081313Z Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
2020-09-08T19:40:54.387083813Z  ---> Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated in table 'devnuget.dbo.Packages', column 'ReleaseNotes'. Truncated value: 'Version: 6.0.0
2020-09-08T19:40:54.387086213Z Availability: NET Standard 2.0
2020-09-08T19:40:54.387088213Z  
2020-09-08T19:40:54.387090313Z # Upgrade Steps
2020-09-08T19:40:54.387092213Z - The Cuemon.Serialization.Xml names'.
2020-09-08T19:40:54.387094113Z The statement has been terminated.
2020-09-08T19:40:54.387096013Z    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
2020-09-08T19:40:54.387098313Z    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
2020-09-08T19:40:54.387106113Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2020-09-08T19:40:54.387179414Z --- End of stack trace from previous location where exception was thrown ---
2020-09-08T19:40:54.387185214Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2020-09-08T19:40:54.387188014Z --- End of stack trace from previous location where exception was thrown ---
2020-09-08T19:40:54.387191014Z    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
2020-09-08T19:40:54.387194314Z    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
2020-09-08T19:40:54.387197514Z    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
2020-09-08T19:40:54.387200714Z    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.387204014Z ClientConnectionId:4354eea0-8955-4584-a17a-f3d5a1b11300
2020-09-08T19:40:54.387206914Z Error Number:2628,State:1,Class:16
2020-09-08T19:40:54.387209814Z    --- End of inner exception stack trace ---
2020-09-08T19:40:54.387212614Z    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.387215014Z    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.387217314Z    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
2020-09-08T19:40:54.387224615Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
2020-09-08T19:40:54.387226915Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2020-09-08T19:40:54.387229215Z    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
2020-09-08T19:40:54.387231915Z    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2020-09-08T19:40:54.387234215Z    at BaGet.Core.PackageService.AddAsync(Package package, CancellationToken cancellationToken) in /src/BaGet.Core/PackageService.cs:line 35
2020-09-08T19:40:54.387236515Z    at BaGet.Core.PackageIndexingService.IndexAsync(Stream packageStream, CancellationToken cancellationToken) in /src/BaGet.Core/Indexing/PackageIndexingService.cs:line 163
2020-09-08T19:40:54.387242715Z    at BaGet.Hosting.PackagePublishController.Upload(CancellationToken cancellationToken) in /src/BaGet.Hosting/Controllers/PackagePublishController.cs:line 81
2020-09-08T19:40:54.89577877Z fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
2020-09-08T19:40:54.895852471Z       Failed executing DbCommand (21ms) [Parameters=[@p0='?' (Size = 4000), @p1='?' (Size = 4000), @p2='?' (DbType = Int64), @p3='?' (DbType = Boolean), @p4='?' (DbType = Boolean), @p5='?' (Size = 4000), @p6='?' (Size = 128), @p7='?' (DbType = Boolean), @p8='?' (Size = 20), @p9='?' (Size = 4000), @p10='?' (DbType = Boolean), @p11='?' (Size = 44), @p12='?' (Size = 64), @p13='?' (Size = 64), @p14='?' (Size = 4000), @p15='?' (DbType = DateTime2), @p16='?' (Size = -1), @p17='?' (Size = 100), @p18='?' (Size = 4000), @p19='?' (DbType = Boolean), @p20='?' (DbType = Int32), @p21='?' (Size = 4000), @p22='?' (Size = 4000), @p23='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
2020-09-08T19:40:54.895873971Z       SET NOCOUNT ON;
2020-09-08T19:40:54.895884871Z       INSERT INTO [Packages] ([Authors], [Description], [Downloads], [HasEmbeddedIcon], [HasReadme], [IconUrl], [Id], [IsPrerelease], [Language], [LicenseUrl], [Listed], [MinClientVersion], [Version], [OriginalVersion], [ProjectUrl], [Published], [ReleaseNotes], [RepositoryType], [RepositoryUrl], [RequireLicenseAcceptance], [SemVerLevel], [Summary], [Tags], [Title])
2020-09-08T19:40:54.895897471Z       VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23);
2020-09-08T19:40:54.895907471Z       SELECT [Key], [RowVersion]
2020-09-08T19:40:54.895916371Z       FROM [Packages]
2020-09-08T19:40:54.895926572Z       WHERE @@ROWCOUNT = 1 AND [Key] = scope_identity();
```

**Comment by gimlichael** [comment]
I changed the column manually to nvarchar(max).
Now I can upload my package.
For reference: https://nuget.cuemon.net/packages/Cuemon.Xml

Keep up the good work - and happy coding :-)

**Comment by viceice** [comment]
Same here with postgresql

```
fail: BaGet.Core.MirrorService[0]
Failed to mirror package documentformat.openxml 2.12.1
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
---> Npgsql.PostgresException (0x80004005): 22001: value too long for type character varying(4000)
at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Exception data:
Severity: ERROR
SqlState: 22001
MessageText: value too long for type character varying(4000)
File: varchar.c
Line: 624
Routine: varchar
--- End of inner exception stack trace ---
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
at BaGet.Core.PackageService.AddAsync(Package package, CancellationToken cancellationToken) in /src/BaGet.Core/PackageService.cs:line 35
at BaGet.Core.PackageIndexingService.IndexAsync(Stream packageStream, CancellationToken cancellationToken) in /src/BaGet.Core/Indexing/PackageIndexingService.cs:line 163
at BaGet.Core.MirrorService.IndexFromSourceAsync(String id, NuGetVersion version, CancellationToken cancellationToken) in /src/BaGet.Core/Mirror/MirrorService.cs:line 245
```

**Comment by loic-sharma** [comment]
This should be fixed by: https://github.com/loic-sharma/BaGet/releases/tag/v0.4.0-preview2

Please let me know if you have additional feedback or suggestions!
