### ISSUE TITLE
Fresh instance of docker container fails and exits immediately

### ISSUE THREAD

**Issue by stefanloerwald** [loic-sharma/BaGet#619]
### Describe the bug

I was experiencing some issues that I think were similar to #604. Since I previously had the mirror enabled, I wanted to disable that, delete all files and simply start fresh. However, my instance fails immediately with

```log
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "__EFMigrationsHistory" (
          "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
          "ProductVersion" TEXT NOT NULL
      );
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at BaGet.Core.AbstractContext`1.RunMigrationsAsync(CancellationToken cancellationToken) in /src/BaGet.Core/Entities/AbstractContext.cs:line 36
   at BaGet.Hosting.IHostExtensions.RunMigrationsAsync(IHost host, CancellationToken cancellationToken) in /src/BaGet.Hosting/Extensions/IHostExtensions.cs:line 35
   at BaGet.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext() in /src/BaGet/Program.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<<OnExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at BaGet.Program.Main(String[] args) in /src/BaGet/Program.cs:line 56
   at BaGet.Program.<Main>(String[] args)
```

### To Reproduce
I have baget deployed in a k8s cluster with the following specification:
```yml
apiVersion: v1
kind: Pod
metadata:
  name: nuget
  labels:
    app: nuget
spec:
  volumes:
    - name: nuget-storage
      persistentVolumeClaim:
        claimName: nuget-storage
  containers:
    - name: nuget-container
      image: loicsharma/baget
      resources:
        requests:
          memory: "200Mi"
          cpu: "25m"
        limits:
          memory: "200Mi"
          cpu: "300m"
      env:
      - name: ApiKey
        value: will-not-tell-you
      - name: Storage__Type
        value: FileSystem
      - name: Storage__Path
        value: "/data/"
      - name: Database__Type
        value: Sqlite
      - name: Database__ConnectionString
        value: "Data Source=/data/baget.db"
      - name: Search__Type
        value: Database
      - name: PackageDeletionBehavior
        value: HardDelete
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/data/"
          name: nuget-storage
```

I have deleted all database&package files, so there shouldn't be anything for baget to get confused by.

Any help would be highly appreciated.

Thanks
Stefan

**Comment by stefanloerwald** [comment]
Nevermind. A reboot of my host machine resolved the issue. My best guess is that this is completely independent of baget.
