### ISSUE TITLE
Starting BaGet using Postgresql server 11

### ISSUE THREAD

**Issue by pazof** [loic-sharma/BaGet#677]
### BaGet using Postgresql server 11
The BaGet server fails at its first db migration.

### To Reproduce
1. Using this version of BaGet 'v0.3.0-preview5'
2. Run this code 'dotnet BaGet.dll'

### Expected behavior
The server starts, having executed its first db migration with success.

### Trace

```
root@lua:/srv/www/baget# dotnet BaGet.dll
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE "TargetFrameworks" ALTER COLUMN "Key" TYPE integer;
      ALTER TABLE "TargetFrameworks" ALTER COLUMN "Key" SET NOT NULL;
      ALTER SEQUENCE "TargetFrameworks_Key_seq" RENAME TO "TargetFrameworks_Key_old_seq";
      ALTER TABLE "TargetFrameworks" ALTER COLUMN "Key" DROP DEFAULT;
      ALTER TABLE "TargetFrameworks" ALTER COLUMN "Key" ADD GENERATED BY DEFAULT AS IDENTITY;
      SELECT * FROM setval('"TargetFrameworks_Key_seq"', nextval('"TargetFrameworks_Key_old_seq"'), false);
      DROP SEQUENCE "TargetFrameworks_Key_old_seq";
Unhandled exception. Npgsql.PostgresException (0x80004005): 42601: erreur de syntaxe sur ou près de « ADD »
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
      at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at BaGet.Core.AbstractContext`1.RunMigrationsAsync(CancellationToken cancellationToken) in D:\a\1\s\src\BaGet.Core\Entities\AbstractContext.cs:line 36
   at BaGet.Database.PostgreSql.PostgreSqlContext.RunMigrationsAsync(CancellationToken cancellationToken) in D:\a\1\s\src\BaGet.Database.PostgreSql\PostgreSqlContext.cs:line 38
   at BaGet.Hosting.IHostExtensions.RunMigrationsAsync(IHost host, CancellationToken cancellationToken) in D:\a\1\s\src\BaGet.Hosting\Extensions\IHostExtensions.cs:line 35
   at BaGet.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext() in D:\a\1\s\src\BaGet\Program.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<<OnExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at BaGet.Program.Main(String[] args) in D:\a\1\s\src\BaGet\Program.cs:line 56
   at BaGet.Program.<Main>(String[] args)
  Exception data:
    Severity: ERREUR
    SqlState: 42601
    MessageText: erreur de syntaxe sur ou près de « ADD »
    Position: 51
    File: scan.l
    Line: 1128
    Routine: scanner_yyerror
Abandon
```

### Additional context

root@lua:/srv/www/baget# uname -a
Linux lua 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux

**Comment by pazof** [comment]
Looking at the migration history, I found these ones : 
```
"20190311172227_Initial";"3.1.1"
"20190914220105_AddOriginalVersionStringColumn";"3.1.1"
"20200109085355_AddReleaseNotesStringColumn";"3.1.1"
```

**Comment by loic-sharma** [comment]
Thanks for reporting! I test BaGet on Postgres 11, so this is definitely unexpected.

**Comment by loic-sharma** [comment]
Are you sure you're using PostgreSQL 11? I wasn't able to reproduce this, and StackOverflow indicates this error happens if you're on an older version: https://stackoverflow.com/questions/51852587/create-an-automatically-increasing-primary-key-column-in-postgresql
